### PR TITLE
Sync knative/pkg branch master to openshift/knative-pkg

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by alanfx** [comment]
@mgencur Hm, any ideas why this PR needs **more** approvers?

**Comment by mgencur** [comment]
@alanfx , I've noticed that https://github.com/openshift/knative-pkg doesn't have properly defined OWNERS and OWNERS_ALIASES. Let me send a PR that fixes that.

**Comment by mgencur** [comment]
Here it is: https://github.com/openshift/knative-pkg/pull/5

**Pull request merged**
